# Generated by Django 5.1.7 on 2025-04-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyLang', '0002_language_lesson_exercise_module_lesson_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
    ]
