# Generated by Django 5.1.7 on 2025-04-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyLang', '0003_remove_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
