# Generated by Django 5.1.7 on 2025-04-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyLang', '0004_language_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, '1/3'), (2, '2/3'), (3, '3/3')]),
        ),
    ]
