# Generated by Django 5.1.7 on 2025-04-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyLang', '0005_alter_lesson_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='theory',
            field=models.JSONField(default=list),
        ),
    ]
