# Generated by Django 5.1.7 on 2025-04-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyLang', '0008_exercise_data_exercise_header_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='header',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='options',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='question',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='data',
            field=models.JSONField(default=dict, help_text='Все данные для задания (включая текст, варианты, ответы, медиа и т.д.)'),
        ),
    ]
