# Generated by Django 5.1.7 on 2025-04-21 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyLang', '0010_lessonprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('response', models.TextField()),
                ('estimation', models.DecimalField(decimal_places=1, max_digits=2)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyLang.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
