# Generated by Django 5.1.7 on 2025-05-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyLang', '0014_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ST', 'Ученик'), ('TC', 'Учитель'), ('CM', 'Модератор'), ('AD', 'Администратор')], default='ST', max_length=2),
        ),
    ]
