# Generated by Django 5.1.7 on 2025-05-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyLang', '0015_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
