# Generated by Django 5.1.7 on 2025-05-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyLang', '0017_review_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Принят'), ('rejected', 'Отклонён')], default='pending', max_length=10),
        ),
    ]
