# Generated by Django 5.1.7 on 2025-05-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyLang', '0018_review_moderation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='is_approved',
            new_name='is_moderated',
        ),
    ]
