# Generated by Django 5.1.7 on 2025-05-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyLang', '0019_rename_is_approved_review_is_moderated'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Заявка выполнена'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_moderated',
            field=models.BooleanField(default=True),
        ),
    ]
