# Generated by Django 5.1.7 on 2025-05-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyLang', '0020_feedback_is_done_alter_review_is_moderated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
